### ISSUE TITLE
Plase help to fix export model after remplace with MXS

### ISSUE THREAD

**Issue by forz0i** [coreynguyen/MXS_Sleeping_Dogs_Definitive_Edition_PC#2]
hello Mr coreynguyen
i have bug after port new Dbs_StrikerA_Body.perm. bin in game
Plase help me to export- after remplace model 
send me tutrial video is possible or text 
my probleme  archive text and  pic 
https://www.mediafire.com/file/jqc19yy53twnuf0/text_read_plase_help_.rar/file

**Comment by coreynguyen** [comment]
I'm not sure what caused the crash you'll need to try to isolate the cause. I would guess it may have to do with the weights since you likely merged it into the SKIN modifier. So, assign all vertices in the skin modifier to a single bone with a strength of 1.0

`
Je ne suis pas sûr de ce qui a causé le crash, vous devrez essayer d'isoler la cause. Je supposerais que cela pourrait avoir à voir avec les poids, car vous les avez probablement fusionnés dans le modificateur SKIN. Donc, assignez tous les sommets dans le modificateur de peau à un seul os avec une force de 1.0.
`

**Comment by forz0i** [comment]
Thank you very much Mr Coreynguyen
I will try to resolve this issue and follow your advice. I have a question when I assign vertex do I assign red only or all vertex colors blue and orange?
Texture how to apply on model I rename like the Sam files or change XML

**Comment by forz0i** [comment]
Hello Mr Coreynguyen
Plase help me send me tutoriel with you tools
Try the program, change a triad db head with another traid thug head in obj fusion and attach format, then put the texture. Please teach me the correct method so that I can finish the mod.
I am getting errors when placing a task
How to maintain the right weight? There are good things in the program like construction, Build, resource manager,.... Please send a simplified explanation so that I can learn this program properly, respecting your time
